<?php

namespace Utils;

class Cipher
{
    private static $method;
    private static $key;


    protected static function iv_bytes()
    {
        return openssl_cipher_iv_length(self::$method);
    }

    public static function code(string|int $data): ?string
    {

        self::$method = config('app.encryption.method');
        self::$key = config('app.encryption.key');

        $iv = openssl_random_pseudo_bytes(self::iv_bytes());
        return bin2hex($iv) . openssl_encrypt($data, self::$method, self::$key, 0, $iv);
    }

    public static function decode(string $data): ?string
    {
        self::$method = config('app.encryption.method');
        self::$key = config('app.encryption.key');

        $iv_strlen = 2  * self::iv_bytes();
        if (preg_match("/^(.{" . $iv_strlen . "})(.+)$/", $data, $regs)) :
            list(, $iv, $crypted_string) = $regs;
            if (ctype_xdigit($iv) && strlen($iv) % 2 == 0) :
                return openssl_decrypt($crypted_string, self::$method, self::$key, 0, hex2bin($iv));
            endif;
            return null;
        endif;

        return null;
    }

    public static function codeAPI(string|int $data): string
    {
        $first_key = base64_decode(config('app.encryption.first_key'));
        $second_key = base64_decode(config('app.encryption.second_key'));

        $method = config('app.encryption.method');
        $iv_length = openssl_cipher_iv_length($method);
        $iv = openssl_random_pseudo_bytes($iv_length);

        $first_encrypted = openssl_encrypt($data, $method, $first_key, OPENSSL_RAW_DATA, $iv);
        $second_encrypted = hash_hmac(config('app.encryption.hash'), $first_encrypted, $second_key, true);

        $output = base64_encode($iv . $second_encrypted . $first_encrypted);

        return urlencode($output);
    }

    public static function decodeAPI(string $input): string|int
    {
        $input = urldecode($input);

        $first_key = base64_decode(config('app.encryption.first_key'));
        $second_key = base64_decode(config('app.encryption.second_key'));

        $mix = base64_decode($input);

        $method = config('app.encryption.method');
        $iv_length = openssl_cipher_iv_length($method);

        $iv = substr($mix, 0, $iv_length);
        $second_encrypted = substr($mix, $iv_length, 64);
        $first_encrypted = substr($mix, $iv_length + 64);

        $data = openssl_decrypt($first_encrypted, $method, $first_key, OPENSSL_RAW_DATA, $iv);
        $second_encrypted_new = hash_hmac(config('app.encryption.hash'), $first_encrypted, $second_key, true);

        if (hash_equals($second_encrypted, $second_encrypted_new)) :
            return $data;
        endif;
    }

    public static function codeFile(string|int $data, ?string $codedFile = null): string
    {
        if (!empty($codedFile)) :
            return $codedFile;
        endif;

        self::$method = config('app.encryption.method');
        self::$key = config('app.encryption.key');


        $iv = openssl_random_pseudo_bytes(self::iv_bytes());
        $data = bin2hex($iv) . openssl_encrypt($data, self::$method, self::$key, 0, $iv);
        $data = str_replace("/", "kush", $data);
        $data = str_replace("=", "bmer", $data);
        $data = str_replace("+", "arya", $data);

        return $data;
    }

    public static function decodeFile(string $data): string|int
    {
        $data = str_replace("kush", "/", $data);
        $data = str_replace("bmer", "=", $data);
        $data = str_replace("arya", "+", $data);

        self::$method = config('app.encryption.method');
        self::$key = config('app.encryption.key');

        $iv_strlen = 2  * self::iv_bytes();
        if (preg_match("/^(.{" . $iv_strlen . "})(.+)$/", $data, $regs)) :
            list(, $iv, $crypted_string) = $regs;
            if (ctype_xdigit($iv) && strlen($iv) % 2 == 0) :
                return openssl_decrypt($crypted_string, self::$method, self::$key, 0, hex2bin($iv));
            endif;
        endif;

        return false;
    }

    public static function codeUuid(string|int $data, ?string $codedFile = null): string
    {

        return self::codeFile($data, $codedFile);
    }

    public static function decodeUuid(string $data): string|int
    {
        return self::decodeFile($data);
    }



    /**
     * Code Decoed Ref numbers
     */
    public static function encodeRefNumber($num)
    {
        $octal = base_convert($num, 10, 8);
        $hex = base_convert($octal, 10, 16);
        return (string) $hex;
    }

    /**
     * Decode referral_code generated by: CONV(CONV(a.id, 10, 8),10,16)
     */
    public static function decodeRefNumber($num)
    {
        $octal = hexdec($num);
        $id = octdec((string)$octal);
        return (int) $id;
    }

    public static function codeMdSha(int $id): string
    {
        return md5(sha1(md5($id)));
    }
}
